#!/bin/bash
# A short script for automatically restarting the display-manager if the script detects something has gone wrong.

_scriptPath=$(realpath $0)
_scriptRoot="$(dirname $(realpath $0))"
_scriptName="$(basename ${_scriptRoot})"

[ $UID -ne 0 ] && SUDO=sudo # Use sudo if not root

cd ${_scriptRoot} || exit 1

[ ! -f .venv/bin/activate ] && python -m venv .venv
. .venv/bin/activate
pip3 install -r requirements.txt

while :
do
  python ./main --exit-on-failure ${@}
  sleep 1
  $SUDO systemctl restart display-manager
done
